version: "3.8"

services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: desafio_php
    container_name: desafio_php
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend:delegated
      - backend_vendor:/var/www/backend/vendor
    environment:
      - APP_ENV=local
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    command: sh -c "php artisan migrate --force && php artisan db:seed --force && php-fpm"

  backend:
    image: nginx:stable-alpine
    container_name: desafio_backend_nginx
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend:ro
      - ./backend/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - php

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend_Angular
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  frontend_dev:
    image: node:22-alpine
    container_name: frontend_dev
    working_dir: /app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mySql
      MYSQL_USER: user_mySql
      MYSQL_PASSWORD: mySqlsenha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  backend_vendor:
